name: app_vendor
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0



dependencies:
  flutter:
    sdk: flutter
  gif: ^2.2.0
  file_picker: ^8.0.0
  flutter_dropzone: ^4.2.1
  dotted_border: ^2.1.0
  flutter_quill: ^11.4.2
  flutter_markdown: ^0.7.7+1 # Attention : ce package est discontinué !
  markdown: ^7.3.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.2.0
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.2.0
  google_sign_in: ^6.1.0 # For Google Sign-In
  flutter_facebook_auth: ^6.1.0 # For Facebook Login
  sign_in_with_apple: ^6.0.0 # For Apple Sign-In
  flutter_web_auth_2: ^4.0.0
  flutter_html: ^3.0.0-alpha.6
  provider: ^6.0.5
  syncfusion_flutter_charts: ^30.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  fl_chart: ^0.68.0
  flutter_lints: ^5.0.0
  uuid: ^4.4.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/



